name: run android automation tests
on: 
 push:
  branches: main
 workflow_dispatch:

jobs:
  run-android-tests:
    runs-on: macos-16.0

    steps:
      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: pull the project in to the runner
        uses: actions/checkout@v3

      - name: setup appium
        run: |
          npm install -g appium
          appium -v
          appium driver install uiautomator2
          appium &>/dev/null &

      - name: run appium android tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: mvn clean test
